/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type ClientId = string;
export type CreatedAt = string;
export type UpdatedAt = string;
export type EndDate = string;
export type StartDate = string;
export type IncomeTrend = "INCREASING" | "DECREASING" | "STABLE";
export type IncomeSourceType = "SALARY" | "BUSINESS" | "INVESTMENT" | "OTHER";
export type Frequency = "MONTHLY" | "YEARLY";
export type Amount = number;
export type Currency = "USD" | "GBP" | "EUR";
export type ReliabilityScore = number;
export type IncomeSources = IncomeSource[];
export type StabilityScore = number;
export type TransactionCategory =
  | "INCOME"
  | "TRANSFER_IN"
  | "TRANSFER_OUT"
  | "LOAN_PAYMENTS"
  | "BANK_FEES"
  | "ENTERTAINMENT"
  | "FOOD_AND_DRINK"
  | "GENERAL_MERCHANDISE"
  | "HOME_IMPROVEMENT"
  | "MEDICAL"
  | "PERSONAL_CARE"
  | "GENERAL_SERVICES"
  | "GOVERNMENT_AND_NON_PROFIT"
  | "TRANSPORTATION"
  | "TRAVEL"
  | "RENT_AND_UTILITIES";
export type TransactionSubcategory =
  | "INCOME_DIVIDENDS"
  | "INCOME_INTEREST_EARNED"
  | "INCOME_RETIREMENT_PENSION"
  | "INCOME_TAX_REFUND"
  | "INCOME_UNEMPLOYMENT"
  | "INCOME_WAGES"
  | "INCOME_OTHER_INCOME"
  | "TRANSFER_IN_CASH_ADVANCES_AND_LOANS"
  | "TRANSFER_IN_DEPOSIT"
  | "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS"
  | "TRANSFER_IN_SAVINGS"
  | "TRANSFER_IN_ACCOUNT_TRANSFER"
  | "TRANSFER_IN_OTHER_TRANSFER_IN"
  | "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS"
  | "TRANSFER_OUT_SAVINGS"
  | "TRANSFER_OUT_WITHDRAWAL"
  | "TRANSFER_OUT_ACCOUNT_TRANSFER"
  | "TRANSFER_OUT_OTHER_TRANSFER_OUT"
  | "LOAN_PAYMENTS_CAR_PAYMENT"
  | "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT"
  | "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT"
  | "LOAN_PAYMENTS_MORTGAGE_PAYMENT"
  | "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT"
  | "LOAN_PAYMENTS_OTHER_PAYMENT"
  | "BANK_FEES_ATM_FEES"
  | "BANK_FEES_FOREIGN_TRANSACTION_FEES"
  | "BANK_FEES_INSUFFICIENT_FUNDS"
  | "BANK_FEES_INTEREST_CHARGE"
  | "BANK_FEES_OVERDRAFT_FEES"
  | "BANK_FEES_OTHER_BANK_FEES"
  | "ENTERTAINMENT_CASINOS_AND_GAMBLING"
  | "ENTERTAINMENT_MUSIC_AND_AUDIO"
  | "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS"
  | "ENTERTAINMENT_TV_AND_MOVIES"
  | "ENTERTAINMENT_VIDEO_GAMES"
  | "ENTERTAINMENT_OTHER_ENTERTAINMENT"
  | "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR"
  | "FOOD_AND_DRINK_COFFEE"
  | "FOOD_AND_DRINK_FAST_FOOD"
  | "FOOD_AND_DRINK_GROCERIES"
  | "FOOD_AND_DRINK_RESTAURANT"
  | "FOOD_AND_DRINK_VENDING_MACHINES"
  | "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK"
  | "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS"
  | "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES"
  | "GENERAL_MERCHANDISE_CONVENIENCE_STORES"
  | "GENERAL_MERCHANDISE_DEPARTMENT_STORES"
  | "GENERAL_MERCHANDISE_DISCOUNT_STORES"
  | "GENERAL_MERCHANDISE_ELECTRONICS"
  | "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES"
  | "GENERAL_MERCHANDISE_OFFICE_SUPPLIES"
  | "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES"
  | "GENERAL_MERCHANDISE_PET_SUPPLIES"
  | "GENERAL_MERCHANDISE_SPORTING_GOODS"
  | "GENERAL_MERCHANDISE_SUPERSTORES"
  | "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE"
  | "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE"
  | "HOME_IMPROVEMENT_FURNITURE"
  | "HOME_IMPROVEMENT_HARDWARE"
  | "HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE"
  | "HOME_IMPROVEMENT_SECURITY"
  | "HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT"
  | "MEDICAL_DENTAL_CARE"
  | "MEDICAL_EYE_CARE"
  | "MEDICAL_NURSING_CARE"
  | "MEDICAL_PHARMACIES_AND_SUPPLEMENTS"
  | "MEDICAL_PRIMARY_CARE"
  | "MEDICAL_VETERINARY_SERVICES"
  | "MEDICAL_OTHER_MEDICAL"
  | "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS"
  | "PERSONAL_CARE_HAIR_AND_BEAUTY"
  | "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING"
  | "PERSONAL_CARE_OTHER_PERSONAL_CARE"
  | "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING"
  | "GENERAL_SERVICES_AUTOMOTIVE"
  | "GENERAL_SERVICES_CHILDCARE"
  | "GENERAL_SERVICES_CONSULTING_AND_LEGAL"
  | "GENERAL_SERVICES_EDUCATION"
  | "GENERAL_SERVICES_INSURANCE"
  | "GENERAL_SERVICES_POSTAGE_AND_SHIPPING"
  | "GENERAL_SERVICES_STORAGE"
  | "GENERAL_SERVICES_OTHER_GENERAL_SERVICES"
  | "GOVERNMENT_AND_NON_PROFIT_DONATIONS"
  | "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES"
  | "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT"
  | "GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT"
  | "TRANSPORTATION_BIKES_AND_SCOOTERS"
  | "TRANSPORTATION_GAS"
  | "TRANSPORTATION_PARKING"
  | "TRANSPORTATION_PUBLIC_TRANSIT"
  | "TRANSPORTATION_TAXIS_AND_RIDE_SHARES"
  | "TRANSPORTATION_TOLLS"
  | "TRANSPORTATION_OTHER_TRANSPORTATION"
  | "TRAVEL_FLIGHTS"
  | "TRAVEL_LODGING"
  | "TRAVEL_RENTAL_CARS"
  | "TRAVEL_OTHER_TRAVEL"
  | "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY"
  | "RENT_AND_UTILITIES_INTERNET_AND_CABLE"
  | "RENT_AND_UTILITIES_RENT"
  | "RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT"
  | "RENT_AND_UTILITIES_TELEPHONE"
  | "RENT_AND_UTILITIES_WATER"
  | "RENT_AND_UTILITIES_OTHER_UTILITIES";
export type Subcategories = SubcategoryBreakdown[];
export type Categories = CategoryBreakdown[];
export type TrendType = "STABLE" | "INCREASING" | "DECREASING";
export type SavingsRatio = number;
export type DebtToIncomeRatio = number;
export type DisposableIncomeRatio = number;
export type PaymentToIncomeRatio = number;
export type RiskFactorTypes =
  | "DEBT_TO_INCOME_RATIO"
  | "SAVINGS_RATIO"
  | "DISPOSABLE_INCOME_RATIO"
  | "PAYMENT_TO_INCOME_RATIO";
export type Message = string;
export type RiskFactors = PositiveFactor[];
export type PositiveFactors = PositiveFactor[];
export type RiskLevel = "LOW" | "MEDIUM" | "HIGH";
export type AffordabilityBuffer = number;
export type IncomeStabilityScore = number;
export type AssessmentType = "AFFORDABILITY" | "RISK" | "FULL";
export type CoApplicantId = string | null;

export interface Assessments {
  id: Id;
  client_id: ClientId;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  analysis_period: AnalysisPeriod;
  assessment_data: AssessmentData;
  assessment_type: AssessmentType;
  co_applicant_id?: CoApplicantId;
  [k: string]: unknown;
}
export interface AnalysisPeriod {
  end_date: EndDate;
  start_date: StartDate;
  [k: string]: unknown;
}
export interface AssessmentData {
  income: Income;
  expenses: Expenses;
  affordability: Affordability;
  risk_assessment: RiskAssessment;
  [k: string]: unknown;
}
export interface Income {
  income_trend: IncomeTrend;
  income_sources: IncomeSources;
  stability_score: StabilityScore;
  monthly_averages: MonthlyAverages;
  annual_projection: MonetaryAmount;
  [k: string]: unknown;
}
export interface IncomeSource {
  name: IncomeSourceType;
  frequency: Frequency;
  monthly_average: MonetaryAmount;
  reliability_score: ReliabilityScore;
  [k: string]: unknown;
}
/**
 * Amount with currency
 */
export interface MonetaryAmount {
  amount: Amount;
  currency: Currency;
  [k: string]: unknown;
}
export interface MonthlyAverages {
  last_3_months: MonetaryAmount;
  last_6_months: MonetaryAmount;
  last_12_months: MonetaryAmount;
  [k: string]: unknown;
}
export interface Expenses {
  fixed_costs: Costs;
  variable_costs: Costs;
  monthly_averages: MonthlyAverages;
  [k: string]: unknown;
}
/**
 * Represents the total costs and breakdown by categories.
 */
export interface Costs {
  total: MonetaryAmount;
  categories: Categories;
  [k: string]: unknown;
}
/**
 * Represents the breakdown of a single category with its subcategories.
 */
export interface CategoryBreakdown {
  total: MonetaryAmount;
  category: TransactionCategory;
  subcategories: Subcategories;
  [k: string]: unknown;
}
/**
 * Represents the breakdown of a single subcategory.
 */
export interface SubcategoryBreakdown {
  amount: MonetaryAmount;
  subcategory: TransactionSubcategory;
  [k: string]: unknown;
}
export interface Affordability {
  metrics: AffordabilityMetrics;
  [k: string]: unknown;
}
export interface AffordabilityMetrics {
  disposable_income: DisposableIncome;
  [k: string]: unknown;
}
export interface DisposableIncome {
  current: MonetaryAmount;
  six_month_trend: TrendType;
  three_month_trend: TrendType;
  [k: string]: unknown;
}
export interface RiskAssessment {
  metrics: RiskAssessmentMetrics;
  risk_factors?: RiskFactors;
  positive_factors?: PositiveFactors;
  overall_risk_level: RiskLevel;
  affordability_buffer: AffordabilityBuffer;
  income_stability_score: IncomeStabilityScore;
  [k: string]: unknown;
}
export interface RiskAssessmentMetrics {
  savings_ratio: SavingsRatio;
  debt_to_income_ratio: DebtToIncomeRatio;
  disposable_income_ratio: DisposableIncomeRatio;
  payment_to_income_ratio: PaymentToIncomeRatio;
  [k: string]: unknown;
}
export interface PositiveFactor {
  type: RiskFactorTypes;
  message: Message;
  [k: string]: unknown;
}
