/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type CreatedAt = string;
export type UpdatedAt = string;
export type DocumentId = string;
export type DocumentType =
  | "BANK_STATEMENT"
  | "PAYSLIP"
  | "UTILITY_BILL"
  | "COUNCIL_TAX"
  | "MORTGAGE_STATEMENT"
  | "CREDIT_CARD_STATEMENT"
  | "INVESTMENT_STATEMENT"
  | "PENSION_STATEMENT"
  | "TAX_DOCUMENT"
  | "OTHER";
export type DocumentMetadata1 = BankStatementData | PayslipData;
export type Iban = string | null;
export type DocumentType1 =
  | "BANK_STATEMENT"
  | "PAYSLIP"
  | "UTILITY_BILL"
  | "COUNCIL_TAX"
  | "MORTGAGE_STATEMENT"
  | "CREDIT_CARD_STATEMENT"
  | "INVESTMENT_STATEMENT"
  | "PENSION_STATEMENT"
  | "TAX_DOCUMENT"
  | "OTHER";
export type Currency = "USD" | "GBP" | "EUR";
export type Amount = number;
export type AccountType = "CURRENT" | "SAVINGS" | "MONEY_MARKET" | "INVESTMENT" | "CREDIT" | "OTHER";
export type AccountHolder = string | null;
export type AccountNumber = string | null;
export type SwiftBic = string | null;
export type LocalBankCode = string | null;
export type BankCodeType = "SORT_CODE" | "ROUTING_NUMBER" | "BANK_STATE_BRANCH_NUMBER";
export type Date = string;
export type TransactionTypes =
  | "BGC"
  | "BP"
  | "CHG"
  | "CHQ"
  | "COR"
  | "CPT"
  | "DD"
  | "DEB"
  | "DEP"
  | "FEE"
  | "FPI"
  | "FPO"
  | "MPI"
  | "MPO"
  | "PAY"
  | "SO"
  | "TFR";
export type TransactionCategory =
  | "INCOME"
  | "TRANSFER_IN"
  | "TRANSFER_OUT"
  | "LOAN_PAYMENTS"
  | "BANK_FEES"
  | "ENTERTAINMENT"
  | "FOOD_AND_DRINK"
  | "GENERAL_MERCHANDISE"
  | "HOME_IMPROVEMENT"
  | "MEDICAL"
  | "PERSONAL_CARE"
  | "GENERAL_SERVICES"
  | "GOVERNMENT_AND_NON_PROFIT"
  | "TRANSPORTATION"
  | "TRAVEL"
  | "RENT_AND_UTILITIES";
export type Confidence = number;
export type Description = string;
export type TransactionSubcategory =
  | "INCOME_DIVIDENDS"
  | "INCOME_INTEREST_EARNED"
  | "INCOME_RETIREMENT_PENSION"
  | "INCOME_TAX_REFUND"
  | "INCOME_UNEMPLOYMENT"
  | "INCOME_WAGES"
  | "INCOME_OTHER_INCOME"
  | "TRANSFER_IN_CASH_ADVANCES_AND_LOANS"
  | "TRANSFER_IN_DEPOSIT"
  | "TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS"
  | "TRANSFER_IN_SAVINGS"
  | "TRANSFER_IN_ACCOUNT_TRANSFER"
  | "TRANSFER_IN_OTHER_TRANSFER_IN"
  | "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS"
  | "TRANSFER_OUT_SAVINGS"
  | "TRANSFER_OUT_WITHDRAWAL"
  | "TRANSFER_OUT_ACCOUNT_TRANSFER"
  | "TRANSFER_OUT_OTHER_TRANSFER_OUT"
  | "LOAN_PAYMENTS_CAR_PAYMENT"
  | "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT"
  | "LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT"
  | "LOAN_PAYMENTS_MORTGAGE_PAYMENT"
  | "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT"
  | "LOAN_PAYMENTS_OTHER_PAYMENT"
  | "BANK_FEES_ATM_FEES"
  | "BANK_FEES_FOREIGN_TRANSACTION_FEES"
  | "BANK_FEES_INSUFFICIENT_FUNDS"
  | "BANK_FEES_INTEREST_CHARGE"
  | "BANK_FEES_OVERDRAFT_FEES"
  | "BANK_FEES_OTHER_BANK_FEES"
  | "ENTERTAINMENT_CASINOS_AND_GAMBLING"
  | "ENTERTAINMENT_MUSIC_AND_AUDIO"
  | "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS"
  | "ENTERTAINMENT_TV_AND_MOVIES"
  | "ENTERTAINMENT_VIDEO_GAMES"
  | "ENTERTAINMENT_OTHER_ENTERTAINMENT"
  | "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR"
  | "FOOD_AND_DRINK_COFFEE"
  | "FOOD_AND_DRINK_FAST_FOOD"
  | "FOOD_AND_DRINK_GROCERIES"
  | "FOOD_AND_DRINK_RESTAURANT"
  | "FOOD_AND_DRINK_VENDING_MACHINES"
  | "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK"
  | "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS"
  | "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES"
  | "GENERAL_MERCHANDISE_CONVENIENCE_STORES"
  | "GENERAL_MERCHANDISE_DEPARTMENT_STORES"
  | "GENERAL_MERCHANDISE_DISCOUNT_STORES"
  | "GENERAL_MERCHANDISE_ELECTRONICS"
  | "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES"
  | "GENERAL_MERCHANDISE_OFFICE_SUPPLIES"
  | "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES"
  | "GENERAL_MERCHANDISE_PET_SUPPLIES"
  | "GENERAL_MERCHANDISE_SPORTING_GOODS"
  | "GENERAL_MERCHANDISE_SUPERSTORES"
  | "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE"
  | "GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE"
  | "HOME_IMPROVEMENT_FURNITURE"
  | "HOME_IMPROVEMENT_HARDWARE"
  | "HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE"
  | "HOME_IMPROVEMENT_SECURITY"
  | "HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT"
  | "MEDICAL_DENTAL_CARE"
  | "MEDICAL_EYE_CARE"
  | "MEDICAL_NURSING_CARE"
  | "MEDICAL_PHARMACIES_AND_SUPPLEMENTS"
  | "MEDICAL_PRIMARY_CARE"
  | "MEDICAL_VETERINARY_SERVICES"
  | "MEDICAL_OTHER_MEDICAL"
  | "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS"
  | "PERSONAL_CARE_HAIR_AND_BEAUTY"
  | "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING"
  | "PERSONAL_CARE_OTHER_PERSONAL_CARE"
  | "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING"
  | "GENERAL_SERVICES_AUTOMOTIVE"
  | "GENERAL_SERVICES_CHILDCARE"
  | "GENERAL_SERVICES_CONSULTING_AND_LEGAL"
  | "GENERAL_SERVICES_EDUCATION"
  | "GENERAL_SERVICES_INSURANCE"
  | "GENERAL_SERVICES_POSTAGE_AND_SHIPPING"
  | "GENERAL_SERVICES_STORAGE"
  | "GENERAL_SERVICES_OTHER_GENERAL_SERVICES"
  | "GOVERNMENT_AND_NON_PROFIT_DONATIONS"
  | "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES"
  | "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT"
  | "GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT"
  | "TRANSPORTATION_BIKES_AND_SCOOTERS"
  | "TRANSPORTATION_GAS"
  | "TRANSPORTATION_PARKING"
  | "TRANSPORTATION_PUBLIC_TRANSIT"
  | "TRANSPORTATION_TAXIS_AND_RIDE_SHARES"
  | "TRANSPORTATION_TOLLS"
  | "TRANSPORTATION_OTHER_TRANSPORTATION"
  | "TRAVEL_FLIGHTS"
  | "TRAVEL_LODGING"
  | "TRAVEL_RENTAL_CARS"
  | "TRAVEL_OTHER_TRAVEL"
  | "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY"
  | "RENT_AND_UTILITIES_INTERNET_AND_CABLE"
  | "RENT_AND_UTILITIES_RENT"
  | "RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT"
  | "RENT_AND_UTILITIES_TELEPHONE"
  | "RENT_AND_UTILITIES_WATER"
  | "RENT_AND_UTILITIES_OTHER_UTILITIES";
export type Income = Transaction[];
export type Savings = Transaction[];
export type Expenses = Transaction[];
export type StatementPeriodEnd = string | null;
export type StatementPeriodStart = string | null;
export type DocumentType2 =
  | "BANK_STATEMENT"
  | "PAYSLIP"
  | "UTILITY_BILL"
  | "COUNCIL_TAX"
  | "MORTGAGE_STATEMENT"
  | "CREDIT_CARD_STATEMENT"
  | "INVESTMENT_STATEMENT"
  | "PENSION_STATEMENT"
  | "TAX_DOCUMENT"
  | "OTHER";
/**
 * Universal deduction types
 */
export type DeductionType =
  | "FEDERAL_INCOME_TAX"
  | "STATE_INCOME_TAX"
  | "SOCIAL_SECURITY"
  | "PENSION"
  | "HEALTH_INSURANCE"
  | "OTHER";
export type Description1 = string | null;
export type Deductions = PayrollDeduction[];
/**
 * Specific payroll exemption types
 */
export type PayrollExemptionType = "PERSONAL_EXEMPTION";
export type Description2 = string | null;
export type Exemptions = PayrollExemption[];
export type EmployeeId = string | null;
export type CountryCode =
  | "AW"
  | "AF"
  | "AO"
  | "AI"
  | "AX"
  | "AL"
  | "AD"
  | "AE"
  | "AR"
  | "AM"
  | "AS"
  | "AQ"
  | "TF"
  | "AG"
  | "AU"
  | "AT"
  | "AZ"
  | "BI"
  | "BE"
  | "BJ"
  | "BQ"
  | "BF"
  | "BD"
  | "BG"
  | "BH"
  | "BS"
  | "BA"
  | "BL"
  | "BY"
  | "BZ"
  | "BM"
  | "BO"
  | "BR"
  | "BB"
  | "BN"
  | "BT"
  | "BV"
  | "BW"
  | "CF"
  | "CA"
  | "CC"
  | "CH"
  | "CL"
  | "CN"
  | "CI"
  | "CM"
  | "CD"
  | "CG"
  | "CK"
  | "CO"
  | "KM"
  | "CV"
  | "CR"
  | "CU"
  | "CW"
  | "CX"
  | "KY"
  | "CY"
  | "CZ"
  | "DE"
  | "DJ"
  | "DM"
  | "DK"
  | "DO"
  | "DZ"
  | "EC"
  | "EG"
  | "ER"
  | "EH"
  | "ES"
  | "EE"
  | "ET"
  | "FI"
  | "FJ"
  | "FK"
  | "FR"
  | "FO"
  | "FM"
  | "GA"
  | "GB"
  | "GE"
  | "GG"
  | "GH"
  | "GI"
  | "GN"
  | "GP"
  | "GM"
  | "GW"
  | "GQ"
  | "GR"
  | "GD"
  | "GL"
  | "GT"
  | "GF"
  | "GU"
  | "GY"
  | "HK"
  | "HM"
  | "HN"
  | "HR"
  | "HT"
  | "HU"
  | "ID"
  | "IM"
  | "IN"
  | "IO"
  | "IE"
  | "IR"
  | "IQ"
  | "IS"
  | "IL"
  | "IT"
  | "JM"
  | "JE"
  | "JO"
  | "JP"
  | "KZ"
  | "KE"
  | "KG"
  | "KH"
  | "KI"
  | "KN"
  | "KR"
  | "KW"
  | "LA"
  | "LB"
  | "LR"
  | "LY"
  | "LC"
  | "LI"
  | "LK"
  | "LS"
  | "LT"
  | "LU"
  | "LV"
  | "MO"
  | "MF"
  | "MA"
  | "MC"
  | "MD"
  | "MG"
  | "MV"
  | "MX"
  | "MH"
  | "MK"
  | "ML"
  | "MT"
  | "MM"
  | "ME"
  | "MN"
  | "MP"
  | "MZ"
  | "MR"
  | "MS"
  | "MQ"
  | "MU"
  | "MW"
  | "MY"
  | "YT"
  | "NA"
  | "NC"
  | "NE"
  | "NF"
  | "NG"
  | "NI"
  | "NU"
  | "NL"
  | "NO"
  | "NP"
  | "NR"
  | "NZ"
  | "OM"
  | "PK"
  | "PA"
  | "PN"
  | "PE"
  | "PH"
  | "PW"
  | "PG"
  | "PL"
  | "PR"
  | "KP"
  | "PT"
  | "PY"
  | "PS"
  | "PF"
  | "QA"
  | "RE"
  | "RO"
  | "RU"
  | "RW"
  | "SA"
  | "SD"
  | "SN"
  | "SG"
  | "GS"
  | "SH"
  | "SJ"
  | "SB"
  | "SL"
  | "SV"
  | "SM"
  | "SO"
  | "PM"
  | "RS"
  | "SS"
  | "ST"
  | "SR"
  | "SK"
  | "SI"
  | "SE"
  | "SZ"
  | "SX"
  | "SC"
  | "SY"
  | "TC"
  | "TD"
  | "TG"
  | "TH"
  | "TJ"
  | "TK"
  | "TM"
  | "TL"
  | "TO"
  | "TT"
  | "TN"
  | "TR"
  | "TV"
  | "TW"
  | "TZ"
  | "UG"
  | "UA"
  | "UM"
  | "UY"
  | "US"
  | "UZ"
  | "VA"
  | "VC"
  | "VE"
  | "VG"
  | "VI"
  | "VN"
  | "VU"
  | "WF"
  | "WS"
  | "YE"
  | "ZA"
  | "ZM"
  | "ZW";
export type ProcessDate = string | null;
export type EmployerName = string | null;
export type LocalTaxCode = string | null;
export type PayPeriodEnd = string | null;
export type TaxIdentifier = string | null;
export type EmployerTaxId = string | null;
export type PayPeriodStart = string | null;
export type EmployerRegistration = string | null;

export interface DocumentMetadata {
  id: Id;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  document_id: DocumentId;
  document_type: DocumentType;
  document_metadata: DocumentMetadata1;
  [k: string]: unknown;
}
export interface BankStatementData {
  iban?: Iban;
  type?: DocumentType1;
  currency: Currency;
  end_balance?: MonetaryAmount | null;
  account_type?: AccountType | null;
  start_balance?: MonetaryAmount | null;
  account_holder?: AccountHolder;
  account_number?: AccountNumber;
  total_money_in?: MonetaryAmount | null;
  bank_identifier: BankIdentifier;
  overdraft_limit?: MonetaryAmount | null;
  total_money_out?: MonetaryAmount | null;
  analysis_results?: AnalysisResults | null;
  statement_period_end?: StatementPeriodEnd;
  statement_period_start?: StatementPeriodStart;
  [k: string]: unknown;
}
/**
 * Amount with currency
 */
export interface MonetaryAmount {
  amount: Amount;
  currency: Currency;
  [k: string]: unknown;
}
/**
 * International bank identification
 */
export interface BankIdentifier {
  swift_bic?: SwiftBic;
  local_bank_code?: LocalBankCode;
  local_bank_code_type?: BankCodeType | null;
  [k: string]: unknown;
}
export interface AnalysisResults {
  summary: Summary;
  categorised_transactions: CategorisedTransactions;
  [k: string]: unknown;
}
export interface Summary {
  total_income: MonetaryAmount;
  total_savings: MonetaryAmount;
  total_expenses: MonetaryAmount;
  monthly_averages: MonthlyAverages;
  [k: string]: unknown;
}
export interface MonthlyAverages {
  income: MonetaryAmount;
  savings: MonetaryAmount;
  expenses: MonetaryAmount;
  [k: string]: unknown;
}
export interface CategorisedTransactions {
  income: Income;
  savings: Savings;
  expenses: Expenses;
  [k: string]: unknown;
}
export interface Transaction {
  date: Date;
  type: TransactionTypes;
  amount: MonetaryAmount;
  balance?: MonetaryAmount | null;
  category: TransactionCategory;
  confidence: Confidence;
  description: Description;
  sub_category: TransactionSubcategory;
  [k: string]: unknown;
}
export interface PayslipData {
  type?: DocumentType2;
  net_pay: MonetaryAmount;
  net_ytd?: MonetaryAmount | null;
  currency: Currency;
  gross_pay: MonetaryAmount;
  gross_ytd?: MonetaryAmount | null;
  deductions?: Deductions;
  exemptions?: Exemptions;
  employee_id?: EmployeeId;
  country_code: CountryCode;
  process_date?: ProcessDate;
  employer_name?: EmployerName;
  local_tax_code?: LocalTaxCode;
  pay_period_end?: PayPeriodEnd;
  tax_identifier?: TaxIdentifier;
  employer_tax_id?: EmployerTaxId;
  pay_period_start?: PayPeriodStart;
  employer_registration?: EmployerRegistration;
  [k: string]: unknown;
}
/**
 * Generic deduction structure
 */
export interface PayrollDeduction {
  type: DeductionType;
  amount: MonetaryAmount;
  description?: Description1;
  year_to_date?: MonetaryAmount | null;
  [k: string]: unknown;
}
/**
 * Generic payroll exemption structure
 */
export interface PayrollExemption {
  type: PayrollExemptionType;
  amount: MonetaryAmount;
  description?: Description2;
  year_to_date?: MonetaryAmount | null;
  [k: string]: unknown;
}
