/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type PageStatus = "PROCESSING" | "COMPLETED" | "FAILED";
export type CreatedAt = string;
export type UpdatedAt = string;
export type DocumentId = string;
export type PageNumber = number;
export type S3JpgPath = string;
export type S3PdfPath = string;
export type Forms =
  | {
      [k: string]: string;
    }[]
  | null;
export type Tables =
  | {
      [k: string]: {
        [k: string]: string;
      }[];
    }[]
  | null;
export type ErrorCode = "PAGE_NOT_FOUND" | "PAGE_NOT_PROCESSABLE" | "PAGE_PROCESSING_FAILED";
export type ErrorMessage = string;

export interface DocumentPages {
  id: Id;
  status: PageStatus;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  document_id: DocumentId;
  page_number: PageNumber;
  s3_jpg_path: S3JpgPath;
  s3_pdf_path: S3PdfPath;
  extracted_data?: ExtractedData | null;
  processing_errors?: ProcessingErrors | null;
  [k: string]: unknown;
}
export interface ExtractedData {
  forms?: Forms;
  tables?: Tables;
  [k: string]: unknown;
}
export interface ProcessingErrors {
  error_code: ErrorCode;
  error_message: ErrorMessage;
  [k: string]: unknown;
}
