/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Name = string;
export type CreatedAt = string;
export type UpdatedAt = string;

export interface JsonSchemas {
  id: Id;
  name: Name;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  json_schema: JsonSchema;
  [k: string]: unknown;
}
export interface JsonSchema {
  [k: string]: unknown;
}
